server:
    servlet:
        context-path: /web/common
    port: 8080
spring:
    application:
        name: adminSpringBoot
    http:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

# -------------------------------- Datasources -------------------------------- #
mysql:
    datasource:
        #jdbc-Url: jdbc:mysql://localhost:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false;useUnicode=true;useJDBCCompliantTimezoneShift=true;useLegacyDatetimeCode=false;serverTimezone=UTC
        jdbc-Url: jdbc:mysql://localhost:3306/hibernate_adminSpringMVC?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=UTF8
        username: root
        password: abc123
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
            poolName: SpringBootHikariPostgres
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                ddl-auto: create
